// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cowboy.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	cowboy.proto

It has these top-level messages:
	GetShotRequest
	GetShotResponse
	StartShootingRequest
	StartShootingResponse
	GetDeclaredVictoriousRequest
	GetDeclaredVictoriousResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetShotRequest struct {
	ShooterName    string `protobuf:"bytes,1,opt,name=shooterName" json:"shooterName,omitempty"`
	IncomingDamage int32  `protobuf:"varint,2,opt,name=incomingDamage" json:"incomingDamage,omitempty"`
}

func (m *GetShotRequest) Reset()                    { *m = GetShotRequest{} }
func (m *GetShotRequest) String() string            { return proto.CompactTextString(m) }
func (*GetShotRequest) ProtoMessage()               {}
func (*GetShotRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetShotRequest) GetShooterName() string {
	if m != nil {
		return m.ShooterName
	}
	return ""
}

func (m *GetShotRequest) GetIncomingDamage() int32 {
	if m != nil {
		return m.IncomingDamage
	}
	return 0
}

type GetShotResponse struct {
	VictimName      string `protobuf:"bytes,1,opt,name=victimName" json:"victimName,omitempty"`
	RemainingHealth int32  `protobuf:"varint,2,opt,name=remainingHealth" json:"remainingHealth,omitempty"`
}

func (m *GetShotResponse) Reset()                    { *m = GetShotResponse{} }
func (m *GetShotResponse) String() string            { return proto.CompactTextString(m) }
func (*GetShotResponse) ProtoMessage()               {}
func (*GetShotResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetShotResponse) GetVictimName() string {
	if m != nil {
		return m.VictimName
	}
	return ""
}

func (m *GetShotResponse) GetRemainingHealth() int32 {
	if m != nil {
		return m.RemainingHealth
	}
	return 0
}

type StartShootingRequest struct {
}

func (m *StartShootingRequest) Reset()                    { *m = StartShootingRequest{} }
func (m *StartShootingRequest) String() string            { return proto.CompactTextString(m) }
func (*StartShootingRequest) ProtoMessage()               {}
func (*StartShootingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StartShootingResponse struct {
}

func (m *StartShootingResponse) Reset()                    { *m = StartShootingResponse{} }
func (m *StartShootingResponse) String() string            { return proto.CompactTextString(m) }
func (*StartShootingResponse) ProtoMessage()               {}
func (*StartShootingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetDeclaredVictoriousRequest struct {
}

func (m *GetDeclaredVictoriousRequest) Reset()                    { *m = GetDeclaredVictoriousRequest{} }
func (m *GetDeclaredVictoriousRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeclaredVictoriousRequest) ProtoMessage()               {}
func (*GetDeclaredVictoriousRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetDeclaredVictoriousResponse struct {
}

func (m *GetDeclaredVictoriousResponse) Reset()                    { *m = GetDeclaredVictoriousResponse{} }
func (m *GetDeclaredVictoriousResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeclaredVictoriousResponse) ProtoMessage()               {}
func (*GetDeclaredVictoriousResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*GetShotRequest)(nil), "GetShotRequest")
	proto.RegisterType((*GetShotResponse)(nil), "GetShotResponse")
	proto.RegisterType((*StartShootingRequest)(nil), "StartShootingRequest")
	proto.RegisterType((*StartShootingResponse)(nil), "StartShootingResponse")
	proto.RegisterType((*GetDeclaredVictoriousRequest)(nil), "GetDeclaredVictoriousRequest")
	proto.RegisterType((*GetDeclaredVictoriousResponse)(nil), "GetDeclaredVictoriousResponse")
}

func init() { proto.RegisterFile("cowboy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x57, 0xc1, 0xa9, 0x47, 0xdd, 0x24, 0xd8, 0x39, 0x8a, 0xab, 0x25, 0x17, 0xd2, 0xab,
	0x08, 0xfa, 0x02, 0xa2, 0x83, 0x79, 0xe5, 0x45, 0x07, 0x22, 0xf3, 0x2a, 0xad, 0x87, 0x36, 0xb0,
	0xe6, 0xd4, 0x34, 0x53, 0x7c, 0x4f, 0x1f, 0x48, 0xec, 0xaa, 0x74, 0xa5, 0xee, 0x2e, 0xfc, 0x21,
	0x5f, 0xbe, 0xff, 0x70, 0xe0, 0x28, 0xa1, 0x8f, 0x98, 0x3e, 0x45, 0x61, 0xc8, 0x12, 0x5f, 0xc0,
	0x60, 0x86, 0x76, 0x9e, 0x91, 0x8d, 0xf0, 0x6d, 0x85, 0xa5, 0x65, 0x01, 0x1c, 0x96, 0x19, 0x91,
	0x45, 0xf3, 0x28, 0x73, 0x1c, 0x3b, 0x81, 0x13, 0x1e, 0x44, 0xcd, 0x88, 0x5d, 0xc2, 0x40, 0xe9,
	0x84, 0x72, 0xa5, 0xd3, 0xa9, 0xcc, 0x65, 0x8a, 0xe3, 0x9d, 0xc0, 0x09, 0x77, 0xa3, 0x56, 0xca,
	0x5f, 0x60, 0xf8, 0xc7, 0x2e, 0x0b, 0xd2, 0x25, 0x32, 0x1f, 0xe0, 0x5d, 0x25, 0x56, 0xe5, 0x0d,
	0x76, 0x23, 0x61, 0x21, 0x0c, 0x0d, 0xe6, 0x52, 0x69, 0xa5, 0xd3, 0x07, 0x94, 0x4b, 0x9b, 0xd5,
	0xec, 0x76, 0xcc, 0x47, 0x70, 0x3a, 0xb7, 0xd2, 0xfc, 0xe0, 0xc9, 0x2a, 0x9d, 0xd6, 0xfa, 0xfc,
	0x0c, 0xdc, 0x56, 0xbe, 0xfe, 0x9a, 0xfb, 0x70, 0x3e, 0x43, 0x3b, 0xc5, 0x64, 0x29, 0x0d, 0xbe,
	0x3e, 0xa9, 0xc4, 0x92, 0x51, 0xb4, 0x2a, 0x7f, 0x1f, 0x5e, 0xc0, 0xe4, 0x9f, 0xfb, 0x35, 0xe0,
	0xfa, 0xcb, 0x81, 0xfe, 0x7d, 0x35, 0x3b, 0x26, 0x60, 0xaf, 0x6e, 0xc6, 0x86, 0x62, 0x73, 0x7e,
	0xde, 0x89, 0x68, 0x95, 0xe6, 0x3d, 0x76, 0x0b, 0xc7, 0x1b, 0x52, 0xcc, 0x15, 0x5d, 0xf2, 0xde,
	0x48, 0x74, 0xbb, 0xf7, 0xd8, 0x33, 0xb8, 0x9d, 0x76, 0x6c, 0x22, 0xb6, 0xb5, 0xf2, 0x7c, 0xb1,
	0xb5, 0x14, 0xef, 0xdd, 0xc1, 0x62, 0xbf, 0x5a, 0x85, 0xab, 0x22, 0x8e, 0xfb, 0xd5, 0xe9, 0xe6,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x0c, 0x26, 0xd7, 0x24, 0x02, 0x00, 0x00,
}
